/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "<Region>",
    "aws_dynamodb_all_tables_region": "<Region>",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "alertstable-dev",
            "region": "<Region>"
        },
        {
            "tableName": "schedulestable-dev",
            "region": "<Region>"
        }
    ],
    "aws_cognito_identity_pool_id": "<Region>:<Pool ID>",
    "aws_cognito_region": "<Region>",
    "aws_user_pools_id": "<Region>_<unique id>",
    "aws_user_pools_web_client_id": "<Web client ID>",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "sbrestapi",
            "endpoint": "https://<value>.execute-api.<Region>.amazonaws.com/dev",
            "region": "<Region>"
        }
    ]
};


export default awsmobile;
